-P "~\Downloads\_ytdlp"
-o "%(uploader)s_%(title)s_%(id)s.%(ext)s" --restrict-filenames
--embed-metadata
-f "bv*[ext=mp4]+ba/b[ext=mp4] / bv*+ba/b" -S "res:2160,fps" --embed-chapters
--embed-sub --sub-langs "en.*,pl" --sub-format "srt/best/ass"
#-x --audio-format mp3 --audio-quality 0 --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
