--ffmpeg-location "~\scoop\apps\ffmpeg-yt-dlp\current\bin"
-P "~\Downloads\_dlp"
-o "%(title)s_%(id)s.%(ext)s" --restrict-filenames
-f "bv*[ext=mp4]+ba/b[ext=mp4]" -S "res:2160,fps" --embed-metadata
#--embed-sub --sub-langs pl --sub-format "ass/srt/best"
#-x --audio-format mp3 --audio-quality 0 --embed-metadata --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""