import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

let sharp;
try {
  ({ default: sharp } = await import("sharp"));
} catch {
  console.error("sharp is unavailable. Run `npm i --no-save sharp@0.35.3` and retry.");
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const svgPath = resolve(here, "../../../assets/pet-dispatcher.svg");
const pngPath = resolve(here, "../../../assets/pet-dispatcher.png");
const modulePath = resolve(here, "../control-plane/icon.ts");

const png = await sharp(readFileSync(svgPath), { density: 384 })
  .resize(512, 512)
  .png({ palette: true, compressionLevel: 9, effort: 10 })
  .toBuffer();

writeFileSync(pngPath, png);
const lines = png.toString("base64").match(/.{1,96}/g)
  .map((line) => `  "${line}"`)
  .join(" +\n");
writeFileSync(
  modulePath,
  `/** GENERATED by scripts/build-icon.mjs from assets/pet-dispatcher.svg. */\n` +
  `export const ICON_PNG_BASE64 =\n${lines};\n\n` +
  `export const ICON_BYTES = Uint8Array.from(atob(ICON_PNG_BASE64), (c) => c.charCodeAt(0));\n`,
);

console.log(`pet-dispatcher icon written: ${png.length} bytes`);
