name: Update Quarto extensions

on:
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.10.18"

      - name: Update extensions
        uses: mcanouil/quarto-extensions-updater@v2
        with:
          github-token: ${{ secrets.GH_PAT }}
          scan-directories: token-worldcup
          update-strategy: minor
